### ISSUE TITLE
Bold / Italic do not respect chosen color

### ISSUE THREAD

**Issue by cmjdev** [yikoyu/vuetify-pro-tiptap#262]
When a selection is bold or italicized it does not respect the current color. It chooses a cyan-ish color.

**Comment by yikoyu** [comment]
chose cyan-ish because of the lines 461-469 in [styles/markdown.scss](https://github.com/yikoyu/vuetify-pro-tiptap/blob/master/src/styles/markdown.scss#L461C1-L469C4)
```scss
  a,
  b,
  strong,
  i,
  em {
    &::selection {
      background-color: var(--cyanosis-slct-elbg-color);
    }
  }
```

If you don't like this style, you can use [custom styles](https://github.com/yikoyu/vuetify-pro-tiptap/blob/master/README.md#custom-theme).

Create markdown.scss
```scss
.vuetify-pro-tiptap-editor__content.markdown-theme-default {
  // your custom styles
  &.__dark {
    // your dark mode custom styles
  }
}
```

Import markdown.scss in main.ts
```ts
// import 'vuetify-pro-tiptap/style.css' // import all(editor and markdown) styles
import 'vuetify-pro-tiptap/styles/editor.css' // only use editor style, not using markdown style
import './styles/markdown.scss'  // your created markdown.scss 
```
